trigger:
- main
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_VERSION: '18.x'

stages:
- stage: Build
  displayName: 'Build and Test'
  jobs:
  - job: Test
    displayName: 'Run Playwright Tests'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: $(NODE_VERSION)
      displayName: 'Install Node.js'

    - script: |
        npm ci
      displayName: 'Install dependencies'

    - script: |
        npx playwright install --with-deps
      displayName: 'Install Playwright browsers'

    - script: |
        npm run lint
      displayName: 'Run linting'

    - script: |
        npx playwright test --project=Chromium
      displayName: 'Run tests on Chromium'

    - script: |
        npx playwright test --project=Firefox
      displayName: 'Run tests on Firefox'

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'test-results/junit.xml'
        mergeTestResults: true
        testRunTitle: 'Playwright Tests'
      condition: succeededOrFailed()
      displayName: 'Publish test results'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: 'playwright-report'
        artifactName: 'playwright-report'
      condition: succeededOrFailed()
      displayName: 'Publish Playwright report'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: 'screenshots'
        artifactName: 'screenshots'
      condition: succeededOrFailed()
      displayName: 'Publish screenshots'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: 'reports'
        artifactName: 'reports'
      condition: succeededOrFailed()
      displayName: 'Publish reports' 